sonata_admin:
    title: 'Template'
    title_logo: img/admin/logo.png
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

    assets:
        extra_stylesheets:
            - https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.2/jquery.fancybox.min.css

        extra_javascripts:
            - https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.2/jquery.fancybox.min.js

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
